# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db_notifications:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  rabbitmq:
    image: rabbitmq:3.7-alpine
    # environment:
    #   - RABBITMQ_DEFAULT_USER=guest
    #   - RABBITMQ_DEFAULT_PASS=guest

  celery:
    image: openzaak/open-notificaties
    environment:
      - DJANGO_SETTINGS_MODULE=nrc.conf.docker
      - SECRET_KEY=${SECRET_KEY:-y8=ynp!*&3z6!0ujpg$0nry%j#1z2@%hq9+1doh1bl+86w)730}
      - RABBITMQ_HOST=rabbitmq
      - PUBLISH_BROKER_URL=amqp://guest:guest@rabbitmq:5672/%2F
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672//
      - CELERY_LOGLEVEL=DEBUG
      - DB_HOST=db_notifications
    command: /celery_worker.sh
    depends_on:
      - db_notifications
      - rabbitmq

  notifications:
    image: openzaak/open-notificaties
    environment:
      - DJANGO_SETTINGS_MODULE=nrc.conf.docker
      - SECRET_KEY=${SECRET_KEY:-y8=ynp!*&3z6!0ujpg$0nry%j#1z2@%hq9+1doh1bl+86w)730}
      - DB_HOST=db_notifications
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      - DEBUG=yes
    volumes:
      - ./fixtures_notificaties:/app/fixtures
    ports:
      - 8001:8000
    depends_on:
      - db_notifications
      - rabbitmq

  db:
    image: mdillon/postgis
    ports:
      - "5432"
    # environment:
    #   - POSTGRES_USER=${PG_USER:zrc}
    #   - POSTGRES_PASSWORD=${PG_PASSWORD:zrc}

  redis:
    image: redis

  mock-endpoints.local:
    image: nginx:1.19
    volumes:
      - ./mocks.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9000:80

  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=openzaak.conf.docker
      - SECRET_KEY=${SECRET_KEY:-7(h1r2hk)8z9+05edulo_3qzymwbo&c24=)qz7+_@3&2sp=u%i}
      - IS_HTTPS=no
      - ALLOWED_HOSTS=localhost
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
      - DEBUG=yes
    volumes:
      - ./fixtures:/app/fixtures
    ports:
      - 8000:8000
    depends_on:
      - db
