version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    environment:
      MINIO_ROOT_USER: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_ROOT_PASSWORD: "${MINIO_SECRET_KEY:-minioadmin}"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      - minio
    environment:
      MC_HOST_myminio: "http://${MINIO_ACCESS_KEY:-minioadmin}:${MINIO_SECRET_KEY:-minioadmin}@minio:9000"
    entrypoint: >
      /bin/sh -c "
      until mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY:-minioadmin} ${MINIO_SECRET_KEY:-minioadmin}; do
        echo 'Waiting for MinIO...'; sleep 2;
      done;
      mc mb --ignore-existing myminio/${MINIO_BUCKET_NAME:-openzaak};
      mc policy set none myminio/${MINIO_BUCKET_NAME:-openzaak};
      "
volumes:
  minio_data:
