---

openzaak_db_port: 5432
openzaak_db_host: /var/run/postgresql
openzaak_db_name: openzaak
openzaak_db_username: openzaak
openzaak_db_password: openzaak

openzaak_secret_key: override-me
openzaak_env_file: /home/openzaak/.env

openzaak_version: '0.9.0'
openzaak_image: openzaak/open-zaak:{{ openzaak_version }}

openzaak_replicas:
  - name: openzaak-0
    port: 8000
  - name: openzaak-1
    port: 8001
  - name: openzaak-2
    port: 8002
