---

# Set up the application secrets

- name: Install secrets
  k8s:
    state: present
    name: opennotificaties-secrets
    namespace: "{{ opennotificaties_namespace }}"
    definition: "{{ lookup('template', 'secrets.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
